# Generated by Django 2.0.4 on 2018-08-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
